In [1]:
import numpy as np

Numpy : https://www.numpy.org/

In [7]:
# scalar
x1 = np.array(1.0)

print(x1.ndim)
print(x1.shape)
print(x1.dtype)

0
()
float64


In [4]:
# vector 

x1 = np.array([1.0, 2.0, 3.0])
x2 = np.array([1, 2, 3])

print(type(x1))
print(type(x2))

print(x1.ndim)
print(x1.shape)
print(x1.dtype)

print(x2.ndim)
print(x2.shape)
print(x2.dtype)




<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
1
(3,)
float64
1
(3,)
int64


In [5]:
# vector 연산
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

print(x + y)
print(x - y)
print(x * y)
print(x / y)


[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [10]:
# matrix 
A = np.array([[1, 2], [3, 4]]) # dtype=np.float64

print(A)
print(A.ndim)
print(A.shape)
print(A.dtype)

[[1. 2.]
 [3. 4.]]
2
(2, 2)
float64


In [12]:
# matrix 연산
A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 3], [2, 1]])

print(A)
print(B)

# element-wise operation
print(A + B)
print(A - B)
print(A * B)
print(A / B)



[[1 2]
 [3 4]]
[[4 3]
 [2 1]]
[[5 5]
 [5 5]]
[[-3 -1]
 [ 1  3]]
[[4 6]
 [6 4]]
[[0.25       0.66666667]
 [1.5        4.        ]]


In [13]:
# Broadcast
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])

print(A * B)

[[10 40]
 [30 80]]


In [16]:
# numpy matrix muliplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 3], [2, 1]])

print(A, B)

print(np.dot(A, B))
print(np.dot(B, A))



[[1 2]
 [3 4]] [[4 3]
 [2 1]]
[[4 3]
 [2 1]]
[[ 8  5]
 [20 13]]
[[13 20]
 [ 5  8]]


In [22]:
# matrix slicing
A = np.array([[1, 2], [3, 4]])

print(A[0, 0])
print(A[0, 1])
print(A[1, 0])
print(A[1, 1])

print(A[:, 0])

print(A[0, :])
print(A[0])

1
2
3
4
[1 3]
[1 2]
[1 2]


In [27]:
# matrix Operation (Transpose, reshape)
A = np.array([[1, 2], [3, 4]])

print(A)

print(A.T)
print(A.transpose())

print(A.reshape(1,4))
print(A.reshape(-1,4))

print(A.reshape(4,1))


[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]
[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]
[[1 2 3 4]]


In [42]:
# Random 

np.random.seed(0)

# 0-1
print(np.random.rand(5))
print(np.random.rand(3, 5))

# normal distribution (mean=0)
print(np.random.randn(5))
print(np.random.randn(3, 5))

# numpy.random.randint(low, high=None, size=None)
print(np.random.randint(-10, high=10, size=(2,2)))


[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
[[0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985 0.77815675 0.87001215]]
[ 1.49407907 -0.20515826  0.3130677  -0.85409574 -2.55298982]
[[ 0.6536186   0.8644362  -0.74216502  2.26975462 -1.45436567]
 [ 0.04575852 -0.18718385  1.53277921  1.46935877  0.15494743]
 [ 0.37816252 -0.88778575 -1.98079647 -0.34791215  0.15634897]]
[[-7 -4]
 [ 1  4]]


In [64]:
# example 
np.random.seed(0)

# AND 
X = np.array([
                [0, 0],
                [0, 1],
                [1, 0],
                [1, 1]
            ])

T = np.array([[0], [0], [0], [1]])


W = np.random.randn(2, 1)
b = np.random.randn(1)

print("W : ")
print(W)
print("b : ")
print(b)

# Y = X * W (X : (4,2) , W (2,1)


Y = np.dot(X, W) + b
print(T)
print(Y)

print(T-Y)
print(np.mean((T-Y)**2))


W : 
[[1.76405235]
 [0.40015721]]
b : 
[0.97873798]
[[0]
 [0]
 [0]
 [1]]
[[0.97873798]
 [1.37889519]
 [2.74279033]
 [3.14294754]]
[[-0.97873798]
 [-1.37889519]
 [-2.74279033]
 [-2.14294754]]
3.743600735152331
