In [174]:
text="""A barber is a person. 
a barber is good person. 
a barber is huge person. 
he Knew A Secret! 
The Secret He Kept is huge secret. 
Huge secret. 
His barber kept his word. 
a barber kept his word. 
His barber kept his secret. 
But keeping and keeping such a huge secret to himself was driving the barber crazy. 
the barber went up a huge mountain."""

In [175]:
# 목표 1: Word Seq --> Word-ID Seq

## 세부목표 1: 문장을 토큰화
## 세부목표 2: 단어 Set 및 아이디 부여
## 세부목표 3: Word Seq --> Word-ID Seq

In [176]:
print(text.replace(".", " .").replace("!", " !"))

A barber is a person . 
a barber is good person . 
a barber is huge person . 
he Knew A Secret ! 
The Secret He Kept is huge secret . 
Huge secret . 
His barber kept his word . 
a barber kept his word . 
His barber kept his secret . 
But keeping and keeping such a huge secret to himself was driving the barber crazy . 
the barber went up a huge mountain .


In [177]:
token = text.replace(".", " .").split('\n')
print(token)



['A barber is a person . ', 'a barber is good person . ', 'a barber is huge person . ', 'he Knew A Secret! ', 'The Secret He Kept is huge secret . ', 'Huge secret . ', 'His barber kept his word . ', 'a barber kept his word . ', 'His barber kept his secret . ', 'But keeping and keeping such a huge secret to himself was driving the barber crazy . ', 'the barber went up a huge mountain .']


In [178]:
text_ = text.replace(".", " .").replace("!", " !")
text_ = text_.strip()

In [179]:
text_sent = text_.lower().split('\n')
# print(text_sent)

In [180]:
sent = []

for s in text_sent:
    word_seq = s.split()
    sent.append(word_seq)
    # print(word_seq)

print(sent)

[['a', 'barber', 'is', 'a', 'person', '.'], ['a', 'barber', 'is', 'good', 'person', '.'], ['a', 'barber', 'is', 'huge', 'person', '.'], ['he', 'knew', 'a', 'secret', '!'], ['the', 'secret', 'he', 'kept', 'is', 'huge', 'secret', '.'], ['huge', 'secret', '.'], ['his', 'barber', 'kept', 'his', 'word', '.'], ['a', 'barber', 'kept', 'his', 'word', '.'], ['his', 'barber', 'kept', 'his', 'secret', '.'], ['but', 'keeping', 'and', 'keeping', 'such', 'a', 'huge', 'secret', 'to', 'himself', 'was', 'driving', 'the', 'barber', 'crazy', '.'], ['the', 'barber', 'went', 'up', 'a', 'huge', 'mountain', '.']]


In [181]:
count_dict = {}

for s in sent:
    for w in s:
        if w not in count_dict:
            count_dict[w] = 1
        else:
            count_dict[w] += 1

print(count_dict)

{'a': 8, 'barber': 8, 'is': 4, 'person': 3, '.': 10, 'good': 1, 'huge': 5, 'he': 2, 'knew': 1, 'secret': 6, '!': 1, 'the': 3, 'kept': 4, 'his': 5, 'word': 2, 'but': 1, 'keeping': 2, 'and': 1, 'such': 1, 'to': 1, 'himself': 1, 'was': 1, 'driving': 1, 'crazy': 1, 'went': 1, 'up': 1, 'mountain': 1}


In [182]:
print(count_dict.items())

dict_items([('a', 8), ('barber', 8), ('is', 4), ('person', 3), ('.', 10), ('good', 1), ('huge', 5), ('he', 2), ('knew', 1), ('secret', 6), ('!', 1), ('the', 3), ('kept', 4), ('his', 5), ('word', 2), ('but', 1), ('keeping', 2), ('and', 1), ('such', 1), ('to', 1), ('himself', 1), ('was', 1), ('driving', 1), ('crazy', 1), ('went', 1), ('up', 1), ('mountain', 1)])


vocab_sorted=sorted(count_dict.items(), key=lambda x:x[1], reverse=True)
print(vocab_sorted)

In [183]:
vocab_sorted=sorted(count_dict.items(), key=lambda x:x[1], reverse=True)
print(vocab_sorted)

[('.', 10), ('a', 8), ('barber', 8), ('secret', 6), ('huge', 5), ('his', 5), ('is', 4), ('kept', 4), ('person', 3), ('the', 3), ('he', 2), ('word', 2), ('keeping', 2), ('good', 1), ('knew', 1), ('!', 1), ('but', 1), ('and', 1), ('such', 1), ('to', 1), ('himself', 1), ('was', 1), ('driving', 1), ('crazy', 1), ('went', 1), ('up', 1), ('mountain', 1)]


In [184]:
vocab_dict = {}

for idx, (word, word_count) in enumerate(vocab_sorted):
    # print(word, word_count)
    vocab_dict[word] = idx+1

print(vocab_dict)

{'.': 1, 'a': 2, 'barber': 3, 'secret': 4, 'huge': 5, 'his': 6, 'is': 7, 'kept': 8, 'person': 9, 'the': 10, 'he': 11, 'word': 12, 'keeping': 13, 'good': 14, 'knew': 15, '!': 16, 'but': 17, 'and': 18, 'such': 19, 'to': 20, 'himself': 21, 'was': 22, 'driving': 23, 'crazy': 24, 'went': 25, 'up': 26, 'mountain': 27}


In [185]:
a = [0]*27
a[12] = 1
print(a)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [186]:
b = [0]*27
b[vocab_dict['keeping']] = 1
print(b)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [187]:
a == b

False

In [188]:
sent_idx = []

for s in sent:
    s_id = []
    for w in s:
        w_id = vocab_dict[w]
        s_id.append(w_id)
        print("s_id :", w, w_id, s_id)
    sent_idx.append(s_id)
    print()

# print(sent_idx)
    

s_id : a 2 [2]
s_id : barber 3 [2, 3]
s_id : is 7 [2, 3, 7]
s_id : a 2 [2, 3, 7, 2]
s_id : person 9 [2, 3, 7, 2, 9]
s_id : . 1 [2, 3, 7, 2, 9, 1]

s_id : a 2 [2]
s_id : barber 3 [2, 3]
s_id : is 7 [2, 3, 7]
s_id : good 14 [2, 3, 7, 14]
s_id : person 9 [2, 3, 7, 14, 9]
s_id : . 1 [2, 3, 7, 14, 9, 1]

s_id : a 2 [2]
s_id : barber 3 [2, 3]
s_id : is 7 [2, 3, 7]
s_id : huge 5 [2, 3, 7, 5]
s_id : person 9 [2, 3, 7, 5, 9]
s_id : . 1 [2, 3, 7, 5, 9, 1]

s_id : he 11 [11]
s_id : knew 15 [11, 15]
s_id : a 2 [11, 15, 2]
s_id : secret 4 [11, 15, 2, 4]
s_id : ! 16 [11, 15, 2, 4, 16]

s_id : the 10 [10]
s_id : secret 4 [10, 4]
s_id : he 11 [10, 4, 11]
s_id : kept 8 [10, 4, 11, 8]
s_id : is 7 [10, 4, 11, 8, 7]
s_id : huge 5 [10, 4, 11, 8, 7, 5]
s_id : secret 4 [10, 4, 11, 8, 7, 5, 4]
s_id : . 1 [10, 4, 11, 8, 7, 5, 4, 1]

s_id : huge 5 [5]
s_id : secret 4 [5, 4]
s_id : . 1 [5, 4, 1]

s_id : his 6 [6]
s_id : barber 3 [6, 3]
s_id : kept 8 [6, 3, 8]
s_id : his 6 [6, 3, 8, 6]
s_id : word 12 [6, 3, 8, 6,

In [189]:
for s, s_idx in zip(sent, sent_idx):
    print(s)
    print(s_idx)
    print()

['a', 'barber', 'is', 'a', 'person', '.']
[2, 3, 7, 2, 9, 1]

['a', 'barber', 'is', 'good', 'person', '.']
[2, 3, 7, 14, 9, 1]

['a', 'barber', 'is', 'huge', 'person', '.']
[2, 3, 7, 5, 9, 1]

['he', 'knew', 'a', 'secret', '!']
[11, 15, 2, 4, 16]

['the', 'secret', 'he', 'kept', 'is', 'huge', 'secret', '.']
[10, 4, 11, 8, 7, 5, 4, 1]

['huge', 'secret', '.']
[5, 4, 1]

['his', 'barber', 'kept', 'his', 'word', '.']
[6, 3, 8, 6, 12, 1]

['a', 'barber', 'kept', 'his', 'word', '.']
[2, 3, 8, 6, 12, 1]

['his', 'barber', 'kept', 'his', 'secret', '.']
[6, 3, 8, 6, 4, 1]

['but', 'keeping', 'and', 'keeping', 'such', 'a', 'huge', 'secret', 'to', 'himself', 'was', 'driving', 'the', 'barber', 'crazy', '.']
[17, 13, 18, 13, 19, 2, 5, 4, 20, 21, 22, 23, 10, 3, 24, 1]

['the', 'barber', 'went', 'up', 'a', 'huge', 'mountain', '.']
[10, 3, 25, 26, 2, 5, 27, 1]



In [190]:
lengths = []
for s in sent_idx:
    len_sent = len(s)
    lengths.append(len_sent)
    
print(lengths)
    

[6, 6, 6, 5, 8, 3, 6, 6, 6, 16, 8]


In [191]:
max_length = max(lengths)
print(max_length)

16


In [192]:
max_length = 0
for s in sent_idx:
    len_sent = len(s)
    if len_sent > max_length:
        max_length = len_sent
    
print(max_length)

16


In [193]:
sent_idx_zeropadded = []

for s in sent_idx:
    # print(s)
    temp = [0]*max_length
    for idx, w_id in enumerate(s):
        temp[idx] = s[idx]
    # print(temp)
    sent_idx_zeropadded.append(temp)
    # break

print(sent_idx_zeropadded)
        

[[2, 3, 7, 2, 9, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [2, 3, 7, 14, 9, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [2, 3, 7, 5, 9, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [11, 15, 2, 4, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [10, 4, 11, 8, 7, 5, 4, 1, 0, 0, 0, 0, 0, 0, 0, 0], [5, 4, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [6, 3, 8, 6, 12, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [2, 3, 8, 6, 12, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [6, 3, 8, 6, 4, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [17, 13, 18, 13, 19, 2, 5, 4, 20, 21, 22, 23, 10, 3, 24, 1], [10, 3, 25, 26, 2, 5, 27, 1, 0, 0, 0, 0, 0, 0, 0, 0]]


In [194]:
import numpy as np

data_X = np.asarray(sent_idx_zeropadded, dtype=np.float32)



In [195]:
print(data_X.shape)
print(type(data_X[0]))
print(data_X[0])

(11, 16)
<class 'numpy.ndarray'>
[2. 3. 7. 2. 9. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [196]:
print(data_X)
data_Y= np.roll(data_X, shift=-1, axis=1)
for row in range(0, len(data_Y)):
    # print(row)
    data_Y[row, len(data_Y[row])-1] = 0 
print(data_Y)

[[ 2.  3.  7.  2.  9.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 2.  3.  7. 14.  9.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 2.  3.  7.  5.  9.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [11. 15.  2.  4. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [10.  4. 11.  8.  7.  5.  4.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 5.  4.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 6.  3.  8.  6. 12.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 2.  3.  8.  6. 12.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 6.  3.  8.  6.  4.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [17. 13. 18. 13. 19.  2.  5.  4. 20. 21. 22. 23. 10.  3. 24.  1.]
 [10.  3. 25. 26.  2.  5. 27.  1.  0.  0.  0.  0.  0.  0.  0.  0.]]
[[ 3.  7.  2.  9.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 3.  7. 14.  9.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 3.  7.  5.  9.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [15.  2.  4. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.

In [197]:
from keras.utils import to_categorical

print(vocab_dict)
num_classes = len(vocab_dict) + 1
print(num_classes)
print(data_X)
data_XX = to_categorical(data_X, num_classes)

{'.': 1, 'a': 2, 'barber': 3, 'secret': 4, 'huge': 5, 'his': 6, 'is': 7, 'kept': 8, 'person': 9, 'the': 10, 'he': 11, 'word': 12, 'keeping': 13, 'good': 14, 'knew': 15, '!': 16, 'but': 17, 'and': 18, 'such': 19, 'to': 20, 'himself': 21, 'was': 22, 'driving': 23, 'crazy': 24, 'went': 25, 'up': 26, 'mountain': 27}
28
[[ 2.  3.  7.  2.  9.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 2.  3.  7. 14.  9.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 2.  3.  7.  5.  9.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [11. 15.  2.  4. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [10.  4. 11.  8.  7.  5.  4.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 5.  4.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 6.  3.  8.  6. 12.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 2.  3.  8.  6. 12.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 6.  3.  8.  6.  4.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [17. 13. 18. 13. 19.  2.  5.  4. 20. 21. 22. 23. 10.  3. 24.  1.]
 [10.  3. 25.

In [198]:
print(data_XX)

[[[0. 0. 1. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 1. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 1. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 1. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 1. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]]


In [199]:
data_XX = to_categorical(data_X, num_classes)
data_YY = to_categorical(data_Y, num_classes)

In [200]:
# import keras
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.layers import SimpleRNN
from keras import initializers
from keras.optimizers import RMSprop

hidden_units = 100
batch_size = 2
epochs = 100
learning_rate = 0.01

x_train = data_XX
y_train = data_YY

x_test = data_XX
y_test = data_YY

print("x_train.shape[1:] : ", x_train.shape[1:])

model = Sequential()
model.add(SimpleRNN(hidden_units,
                    return_sequences=True,
                    input_shape=x_train.shape[1:]))
model.add(Dense(num_classes))
model.add(Activation('softmax'))
rmsprop = RMSprop(lr=learning_rate)
model.compile(loss='categorical_crossentropy',
              optimizer=rmsprop,
              metrics=['accuracy'])

model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_test, y_test))

scores = model.evaluate(x_test, y_test, verbose=1)

print('SimpleRNN test loss    : ', scores[0])
print('SimpleRNN test accuracy: ', scores[1])

x_train.shape[1:] :  (16, 28)
Train on 11 samples, validate on 11 samples
Epoch 1/100
11/11 [==============================] - 3s 228ms/step - loss: 2.0477 - acc: 0.4830 - val_loss: 6.5402 - val_acc: 0.2614
Epoch 2/100
11/11 [==============================] - 0s 5ms/step - loss: 3.5133 - acc: 0.3239 - val_loss: 2.1634 - val_acc: 0.6364
Epoch 3/100
11/11 [==============================] - 0s 5ms/step - loss: 2.2393 - acc: 0.6023 - val_loss: 2.4032 - val_acc: 0.6080
Epoch 4/100
11/11 [==============================] - 0s 6ms/step - loss: 2.1105 - acc: 0.6705 - val_loss: 1.6585 - val_acc: 0.6818
Epoch 5/100
11/11 [==============================] - 0s 5ms/step - loss: 1.9260 - acc: 0.6818 - val_loss: 2.4777 - val_acc: 0.2159
Epoch 6/100
11/11 [==============================] - 0s 4ms/step - loss: 1.7956 - acc: 0.6648 - val_loss: 1.3028 - val_acc: 0.8466
Epoch 7/100
11/11 [==============================] - 0s 5ms/step - loss: 0.9147 - acc: 0.8295 - val_loss: 2.3166 - val_acc: 0.4943
Epoch 8

11/11 [==============================] - 0s 5ms/step - loss: 0.0773 - acc: 0.9659 - val_loss: 0.0550 - val_acc: 0.9716
Epoch 63/100
11/11 [==============================] - 0s 4ms/step - loss: 0.0735 - acc: 0.9659 - val_loss: 0.0537 - val_acc: 0.9716
Epoch 64/100
11/11 [==============================] - 0s 4ms/step - loss: 0.0766 - acc: 0.9545 - val_loss: 0.0622 - val_acc: 0.9716
Epoch 65/100
11/11 [==============================] - 0s 4ms/step - loss: 0.0851 - acc: 0.9545 - val_loss: 0.0555 - val_acc: 0.9716
Epoch 66/100
11/11 [==============================] - 0s 4ms/step - loss: 0.0688 - acc: 0.9659 - val_loss: 0.0533 - val_acc: 0.9716
Epoch 67/100
11/11 [==============================] - 0s 4ms/step - loss: 0.0806 - acc: 0.9602 - val_loss: 0.0676 - val_acc: 0.9716
Epoch 68/100
11/11 [==============================] - 0s 4ms/step - loss: 0.0770 - acc: 0.9716 - val_loss: 0.0613 - val_acc: 0.9716
Epoch 69/100
11/11 [==============================] - 0s 4ms/step - loss: 0.0838 - acc: 0

In [201]:
pred_x_test = model.predict(x_test)

print(pred_x_test[0][0])
print(np.argmax(pred_x_test[0][0]))

print(y_test[0][0])
print(np.argmax(y_test[0][0]))

print("PRED:")
print(np.argmax(pred_x_test, axis=-1))

print("REF :")
print(np.argmax(y_test, axis=-1))

[2.23311054e-05 1.42497711e-05 5.24604926e-04 9.90189254e-01
 4.08342807e-03 1.23809476e-03 2.31980652e-04 7.36791582e-04
 9.43565974e-04 3.02513654e-04 3.37153119e-06 1.98489238e-06
 9.60362435e-04 4.73743557e-06 6.57414901e-04 1.75848027e-06
 3.08952121e-06 4.70632074e-07 1.58724322e-06 1.23103109e-06
 1.06868647e-05 1.01748828e-05 4.48116180e-06 3.09535471e-06
 1.45168615e-05 5.21358470e-06 2.72324746e-06 2.62664907e-05]
3
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
3
PRED:
[[ 3  7  5  9  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  7  5  9  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  7  5  9  1  0  0  0  0  0  0  0  0  0  0  0]
 [15  2  4 16  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 4 11  8  7  5  4 20 21  0  0  0  0  0  0  0  0]
 [ 4  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  8  6  4  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  7  6 12  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  8  6  4  1  0  0  0  0  0  0  0  0  0  0  0]
 [13 18 13 19  2

In [202]:
# import keras
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.layers import LSTM
from keras import initializers
from keras.optimizers import RMSprop

hidden_units = 100
batch_size = 2
epochs = 100
learning_rate = 0.01

x_train = data_XX
y_train = data_YY

x_test = data_XX
y_test = data_YY

print("x_train.shape[1:] : ", x_train.shape[1:])

model = Sequential()
model.add(LSTM(hidden_units,
               return_sequences=True,
               input_shape=x_train.shape[1:]))
model.add(Dense(num_classes))
model.add(Activation('softmax'))
rmsprop = RMSprop(lr=learning_rate)
model.compile(loss='categorical_crossentropy',
              optimizer=rmsprop,
              metrics=['accuracy'])

model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_test, y_test))

scores = model.evaluate(x_test, y_test, verbose=1)

print('LSTM test loss    : ', scores[0])
print('LSTM test accuracy: ', scores[1])

x_train.shape[1:] :  (16, 28)
Train on 11 samples, validate on 11 samples
Epoch 1/100
11/11 [==============================] - 2s 222ms/step - loss: 2.2859 - acc: 0.5114 - val_loss: 1.2626 - val_acc: 0.6591
Epoch 2/100
11/11 [==============================] - 0s 12ms/step - loss: 1.3635 - acc: 0.6705 - val_loss: 1.2434 - val_acc: 0.6591
Epoch 3/100
11/11 [==============================] - 0s 11ms/step - loss: 1.2323 - acc: 0.6648 - val_loss: 1.0766 - val_acc: 0.6932
Epoch 4/100
11/11 [==============================] - 0s 14ms/step - loss: 1.2095 - acc: 0.7102 - val_loss: 1.0731 - val_acc: 0.7045
Epoch 5/100
11/11 [==============================] - 0s 14ms/step - loss: 1.0652 - acc: 0.7102 - val_loss: 1.2449 - val_acc: 0.6932
Epoch 6/100
11/11 [==============================] - 0s 10ms/step - loss: 1.2222 - acc: 0.7102 - val_loss: 1.0874 - val_acc: 0.8239
Epoch 7/100
11/11 [==============================] - 0s 12ms/step - loss: 0.9755 - acc: 0.8011 - val_loss: 0.8631 - val_acc: 0.8239
E

11/11 [==============================] - 0s 13ms/step - loss: 0.0639 - acc: 0.9545 - val_loss: 0.0524 - val_acc: 0.9716
Epoch 63/100
11/11 [==============================] - 0s 12ms/step - loss: 0.0659 - acc: 0.9602 - val_loss: 0.0526 - val_acc: 0.9716
Epoch 64/100
11/11 [==============================] - 0s 13ms/step - loss: 0.0646 - acc: 0.9659 - val_loss: 0.0500 - val_acc: 0.9716
Epoch 65/100
11/11 [==============================] - 0s 11ms/step - loss: 0.0629 - acc: 0.9716 - val_loss: 0.0501 - val_acc: 0.9716
Epoch 66/100
11/11 [==============================] - 0s 11ms/step - loss: 0.0641 - acc: 0.9545 - val_loss: 0.0496 - val_acc: 0.9716
Epoch 67/100
11/11 [==============================] - 0s 12ms/step - loss: 0.0613 - acc: 0.9602 - val_loss: 0.0489 - val_acc: 0.9716
Epoch 68/100
11/11 [==============================] - 0s 11ms/step - loss: 0.0609 - acc: 0.9716 - val_loss: 0.0484 - val_acc: 0.9716
Epoch 69/100
11/11 [==============================] - 0s 11ms/step - loss: 0.0613 

In [203]:
pred_x_test = model.predict(x_test)

print(pred_x_test[0][0])
print(np.argmax(pred_x_test[0][0]))

print(y_test[0][0])
print(np.argmax(y_test[0][0]))

print("PRED:")
print(np.argmax(pred_x_test, axis=-1))

print("REF :")
print(np.argmax(y_test, axis=-1))

[3.95732542e-07 4.05812841e-08 1.12221032e-05 9.98842597e-01
 7.14005379e-04 1.11933245e-04 4.51965292e-07 1.83859142e-04
 9.79927645e-05 2.84290923e-06 2.18841876e-07 4.38682292e-07
 1.63867953e-05 1.09819290e-07 1.45747044e-05 3.65063414e-07
 2.70845391e-07 1.99678965e-07 2.10844490e-07 3.10007636e-07
 1.63577525e-07 2.09492583e-07 3.45573113e-07 3.83136694e-07
 2.30446020e-07 3.04655279e-09 3.06173504e-08 8.73914061e-08]
3
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
3
PRED:
[[ 3  7  5  9  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  7  5  9  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  7  5  9  1  0  0  0  0  0  0  0  0  0  0  0]
 [15  2  4 16  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 3 11  8  7  5  4  1  0  0  0  0  0  0  0  0  0]
 [ 4  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  8  6  4  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  7  6 12  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  8  6  4  1  0  0  0  0  0  0  0  0  0  0  0]
 [13 18 13 19  2

In [204]:
# import keras
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.layers import LSTM, Embedding
from keras import initializers
from keras.optimizers import RMSprop

word_embedding_size = 100
vocab_size = len(vocab_dict) + 1

hidden_units = 100
batch_size = 2
epochs = 100
learning_rate = 0.01

x_train = data_X
y_train = data_YY

x_test = data_X
y_test = data_YY

print("x_train.shape[1:] : ", x_train.shape[1:])

model = Sequential()
model.add(Embedding(vocab_size, word_embedding_size, input_length=x_train.shape[1]))
# the model will take as input an integer matrix of size (batch, input_length).
# the largest integer (i.e. word index) in the input should be
# no larger than 999 (vocabulary size).
# now model.output_shape == (None, 10, 64), where None is the batch dimension.

model.add(LSTM(hidden_units,
               return_sequences=True,
               input_shape=x_train.shape[1:]))
model.add(LSTM(hidden_units,
               return_sequences=True))
               # input_shape=x_train.shape[1:]))
model.add(Dense(num_classes))
model.add(Activation('softmax'))
rmsprop = RMSprop(lr=learning_rate)
model.compile(loss='categorical_crossentropy',
              optimizer=rmsprop,
              metrics=['accuracy'])

model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_test, y_test))

scores = model.evaluate(x_test, y_test, verbose=1)

print('LSTM test loss    : ', scores[0])
print('LSTM test accuracy: ', scores[1])

model.summary()

x_train.shape[1:] :  (16,)
Train on 11 samples, validate on 11 samples
Epoch 1/100
11/11 [==============================] - 3s 306ms/step - loss: 2.1292 - acc: 0.5114 - val_loss: 1.5838 - val_acc: 0.6307
Epoch 2/100
11/11 [==============================] - 0s 18ms/step - loss: 1.8752 - acc: 0.5170 - val_loss: 1.2844 - val_acc: 0.6307
Epoch 3/100
11/11 [==============================] - 0s 19ms/step - loss: 1.3394 - acc: 0.6307 - val_loss: 1.5068 - val_acc: 0.6534
Epoch 4/100
11/11 [==============================] - 0s 19ms/step - loss: 1.3665 - acc: 0.6705 - val_loss: 1.1752 - val_acc: 0.6364
Epoch 5/100
11/11 [==============================] - 0s 20ms/step - loss: 1.1154 - acc: 0.6761 - val_loss: 1.0076 - val_acc: 0.6875
Epoch 6/100
11/11 [==============================] - 0s 18ms/step - loss: 1.0461 - acc: 0.7045 - val_loss: 0.9564 - val_acc: 0.7500
Epoch 7/100
11/11 [==============================] - 0s 20ms/step - loss: 0.9501 - acc: 0.7500 - val_loss: 0.8839 - val_acc: 0.7784
Epoc

11/11 [==============================] - 0s 20ms/step - loss: 0.0638 - acc: 0.9659 - val_loss: 0.0484 - val_acc: 0.9716
Epoch 63/100
11/11 [==============================] - 0s 26ms/step - loss: 0.0611 - acc: 0.9602 - val_loss: 0.0497 - val_acc: 0.9716
Epoch 64/100
11/11 [==============================] - 0s 20ms/step - loss: 0.0601 - acc: 0.9602 - val_loss: 0.0488 - val_acc: 0.9716
Epoch 65/100
11/11 [==============================] - 0s 18ms/step - loss: 0.0565 - acc: 0.9716 - val_loss: 0.0480 - val_acc: 0.9716
Epoch 66/100
11/11 [==============================] - 0s 15ms/step - loss: 0.0608 - acc: 0.9602 - val_loss: 0.0496 - val_acc: 0.9716
Epoch 67/100
11/11 [==============================] - 0s 21ms/step - loss: 0.0605 - acc: 0.9659 - val_loss: 0.0485 - val_acc: 0.9716
Epoch 68/100
11/11 [==============================] - 0s 22ms/step - loss: 0.0598 - acc: 0.9659 - val_loss: 0.0485 - val_acc: 0.9716
Epoch 69/100
11/11 [==============================] - 0s 21ms/step - loss: 0.0599 

In [205]:
pred_x_test = model.predict(x_test)

print(pred_x_test[0][0])
print(np.argmax(pred_x_test[0][0]))

print(y_test[0][0])
print(np.argmax(y_test[0][0]))

print("PRED:")
print(np.argmax(pred_x_test, axis=-1))

print("REF :")
print(np.argmax(y_test, axis=-1))

[2.4989556e-06 4.3600053e-08 2.3447221e-05 9.9939024e-01 5.2770972e-04
 1.9750378e-05 7.6117551e-08 3.6144820e-06 5.6358299e-06 4.1778785e-07
 1.3648093e-07 2.0916534e-07 9.1166921e-06 2.5333975e-09 1.5537978e-05
 2.4682583e-07 2.1015076e-08 1.6741654e-07 1.5881608e-07 2.3291724e-07
 9.8057846e-08 1.1981598e-07 5.5200534e-08 2.8253012e-07 5.2715837e-08
 1.1915068e-08 2.6876538e-08 3.3931027e-08]
3
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
3
PRED:
[[ 3  7  2  9  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  7  2  9  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  7  2  9  1  0  0  0  0  0  0  0  0  0  0  0]
 [15  2  4 16  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 3 11  8  7  5  4  1  0  0  0  0  0  0  0  0  0]
 [ 4  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  8  6 12  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  7  6 12  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  8  6 12  1  0  0  0  0  0  0  0  0  0  0  0]
 [13 18 13 19  2  5  4 20 21 22 23 10  3 24  

In [206]:
print(model.layers[0])
emebdding_layer = model.layers[0]

In [207]:
embeddings = model.layers[0].get_weights()[0]

words_embeddings = {w:embeddings[idx] for w, idx in vocab_dict.items()}
print(words_embeddings)

print(words_embeddings['barber'])

{'.': array([-0.13778307,  0.84110916,  0.66433126,  0.11956102,  0.32808262,
       -0.38334334, -0.28741267, -0.4025532 ,  0.7828784 ,  0.05417778,
        0.5828485 , -0.4213726 , -0.40576053, -0.04384682,  0.19760506,
       -0.3636471 , -0.25753638,  0.35240605, -0.31055078,  0.13211852,
        0.5220053 ,  0.31980762, -0.33987084,  0.31706208,  0.1601418 ,
       -0.73442745, -0.24030505, -0.47462854,  0.29781175,  0.07220611,
       -0.01764157,  0.34051502, -0.02193841, -0.19588548, -0.25769347,
        0.55673015,  0.27762407,  0.51636773, -0.46597013, -0.40896323,
       -0.04641417,  0.30810094,  0.2532996 , -0.19441861, -0.26800898,
       -0.5372454 ,  0.09823105,  0.5135554 , -0.24092518,  0.20084311,
       -0.5397324 ,  0.07274378,  0.33876082, -0.3986542 ,  0.7805507 ,
        0.55476636, -0.83242846,  0.40878826, -0.05832305,  0.33182076,
        0.40938106, -0.43098304,  0.7138856 ,  0.29883102, -0.3523413 ,
        0.20672964, -0.16559055, -0.6675453 , -0.50566524,

In [208]:
# import keras
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.layers import LSTM, Embedding, Bidirectional
from keras import initializers
from keras.optimizers import RMSprop

word_embedding_size = 100
vocab_size = len(vocab_dict) + 1

hidden_units = 100
batch_size = 2
epochs = 100
learning_rate = 0.01

x_train = data_X
y_train = data_YY

x_test = data_X
y_test = data_YY

print("x_train.shape[1:] : ", x_train.shape[1:])

model = Sequential()
model.add(Embedding(vocab_size, word_embedding_size, input_length=x_train.shape[1]))
# the model will take as input an integer matrix of size (batch, input_length).
# the largest integer (i.e. word index) in the input should be
# no larger than 999 (vocabulary size).
# now model.output_shape == (None, 10, 64), where None is the batch dimension.

model.add(Bidirectional(LSTM(hidden_units,
               return_sequences=True,
               input_shape=x_train.shape[1:])))

model.add(Bidirectional(LSTM(hidden_units,
               return_sequences=True)))
               # input_shape=x_train.shape[1:]))
model.add(Dense(num_classes))
model.add(Activation('softmax'))
rmsprop = RMSprop(lr=learning_rate)
model.compile(loss='categorical_crossentropy',
              optimizer=rmsprop,
              metrics=['accuracy'])

model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_test, y_test))

scores = model.evaluate(x_test, y_test, verbose=1)

print('LSTM test loss    : ', scores[0])
print('LSTM test accuracy: ', scores[1])

model.summary()

x_train.shape[1:] :  (16,)
Train on 11 samples, validate on 11 samples
Epoch 1/100
11/11 [==============================] - 5s 410ms/step - loss: 2.5326 - acc: 0.3693 - val_loss: 2.3959 - val_acc: 0.4886
Epoch 2/100
11/11 [==============================] - 0s 22ms/step - loss: 1.7243 - acc: 0.6193 - val_loss: 1.4359 - val_acc: 0.6705
Epoch 3/100
11/11 [==============================] - 0s 21ms/step - loss: 1.5537 - acc: 0.6761 - val_loss: 1.1719 - val_acc: 0.6932
Epoch 4/100
11/11 [==============================] - 0s 23ms/step - loss: 1.2338 - acc: 0.6932 - val_loss: 0.9919 - val_acc: 0.7045
Epoch 5/100
11/11 [==============================] - 0s 22ms/step - loss: 1.0951 - acc: 0.7045 - val_loss: 0.9332 - val_acc: 0.6761
Epoch 6/100
11/11 [==============================] - 0s 22ms/step - loss: 0.8959 - acc: 0.7330 - val_loss: 0.7488 - val_acc: 0.7841
Epoch 7/100
11/11 [==============================] - 0s 22ms/step - loss: 0.7537 - acc: 0.7784 - val_loss: 0.6150 - val_acc: 0.8011
Epoc

11/11 [==============================] - 0s 21ms/step - loss: 5.4084e-07 - acc: 1.0000 - val_loss: 4.6837e-07 - val_acc: 1.0000
Epoch 61/100
11/11 [==============================] - 0s 21ms/step - loss: 4.6803e-07 - acc: 1.0000 - val_loss: 4.1080e-07 - val_acc: 1.0000
Epoch 62/100
11/11 [==============================] - 0s 20ms/step - loss: 4.1046e-07 - acc: 1.0000 - val_loss: 3.5898e-07 - val_acc: 1.0000
Epoch 63/100
11/11 [==============================] - 0s 20ms/step - loss: 3.6034e-07 - acc: 1.0000 - val_loss: 3.2512e-07 - val_acc: 1.0000
Epoch 64/100
11/11 [==============================] - 0s 20ms/step - loss: 3.2478e-07 - acc: 1.0000 - val_loss: 2.9396e-07 - val_acc: 1.0000
Epoch 65/100
11/11 [==============================] - 0s 23ms/step - loss: 2.9294e-07 - acc: 1.0000 - val_loss: 2.5705e-07 - val_acc: 1.0000
Epoch 66/100
11/11 [==============================] - 0s 20ms/step - loss: 2.5637e-07 - acc: 1.0000 - val_loss: 2.3842e-07 - val_acc: 1.0000
Epoch 67/100
11/11 [======

In [209]:
pred_x_test = model.predict(x_test)

print(pred_x_test[0][0])
print(np.argmax(pred_x_test[0][0]))

print(y_test[0][0])
print(np.argmax(y_test[0][0]))

print("PRED:")
print(np.argmax(pred_x_test, axis=-1))

print("REF :")
print(np.argmax(y_test, axis=-1))

[1.7440005e-10 5.9073005e-13 4.3608742e-13 1.0000000e+00 3.5305674e-09
 7.9776016e-14 1.2940489e-12 4.8662527e-09 1.0281051e-08 1.6972599e-14
 1.5247533e-12 2.2429818e-11 2.3484835e-14 2.4010991e-12 1.2775712e-15
 2.6728832e-12 9.9289670e-14 1.3178831e-13 5.2672363e-13 4.3059042e-16
 1.2028978e-13 2.2367763e-13 4.3281405e-14 1.7780398e-12 5.2434449e-11
 7.0216289e-12 1.8587108e-14 1.4519925e-14]
3
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
3
PRED:
[[ 3  7  2  9  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  7 14  9  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  7  5  9  1  0  0  0  0  0  0  0  0  0  0  0]
 [15  2  4 16  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 4 11  8  7  5  4  1  0  0  0  0  0  0  0  0  0]
 [ 4  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  8  6 12  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  8  6 12  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  8  6  4  1  0  0  0  0  0  0  0  0  0  0  0]
 [13 18 13 19  2  5  4 20 21 22 23 10  3 24  